export default {
    hello: "hello",
    hello_greeting: "hello how are you",
    start_chat: "Start Chat",
    no_chats: "No chats, yet!",
    start_new_chat: "Start a new chat",
    you: "You",
    new_chat: "New Chat",
    new_group_chat: "New Group Chat",
    new_announcement: "New Announcement",
    delete_chat: 'Delete Chat',
    no_results: "No results found",




    placeholder:'Search Messages...',
    startchat:'Start Chat',
    reply:'Reply',
    forward:'Forward',
    copy:'Copy',
    star:'Star',
    edit:'Edit',
    delete:'Delete',
    nochat:'No chats, yet!',
    newChat:'New Chat',
    message:'Messages',
    chats:'Chats',
    deletemsg:'This message was deleted.',
    confirmdelete:"Confirm Delete",
    deleteare:"Are you sure you want to delete this message?",
    cancel:"Cancel",
    deleteall:"Confirm Delete All",
    deleteallconfirm:"Are you sure you want to delete all messages?",
    delete_all:"Delete All",
    intercomm:'InterComm',
    homescreen:'HomeScreen',
    favourite:'FavouriteScreen',
    nocontact:'No contacts found',
    searchHere:"Search here",
    viewdetail:'View details',
    pinchat:'Pin chat',
    searchchat:'Search chat',

   }