const Icons = {
    // splash_img: require('./icons/splash_img.png'),
    back: require('./icons/back.png'),
    backicon: require('./icons/backicon.png'),
    add: require('./icons/add.png'),
    adduser:require('./icons/adduser.png'),
    useradd: require('./icons/useradd.png'),
    graySearch: require('./icons/graySearch.png'),
    search: require('./icons/search.png'),
    newChat: require('./icons/newChat.png'),
    groupChat: require('./icons/groupChat.png'),
    announcement: require('./icons/announcement.png'),
    close: require('./icons/close.png'),
    more: require('./icons/more.png'),
    viewDetails: require('./icons/viewDetails.png'),
    pinChat: require('./icons/pinChat.png'),
    searchChat: require('./icons/searchChat.png'),
    deleteChat: require('./icons/deleteChat.png'),
    reply: require('./icons/reply.png'),
    forward: require('./icons/forward.png'),
    copy: require('./icons/copy.png'),
    star: require('./icons/star.png'),
    edit: require('./icons/edit.png'),
    deleteIcon: require('./icons/deleteIcon.png'),
    plus: require('./icons/plus.png'),
    send: require('./icons/send.png'),
  };
  const Images = {
    landing_img: require('./images/landing.png'),
    splash_img: require('./images/splash.png'),
    add: require('./images/add.png'),
    nochat: require('./images/no-chat.png'),
    noResults: require('./images/noResults.png'),
    homeIcon: require('./images/homes.png'),
    settingsIcon: require('./images/star.png'),
    shopIcon: require('./images/user.png'),
    Icon: require('./images/menuIcon.png'),

  };
  
  export {Icons, Images};